"""
tools/__init__.py

Exports all 18 deterministic tool contracts (TC-001..TC-018) per spec/04.
"""

from tools.common import (
    Confidence,
    MechSignature,
    OffsetVerdict,
    ToolResult,
    ToolStatus,
    WaterMechanism,
)
from tools.arps_decline import DeclineFit, fit_decline_curve
from tools.chan_diagnostic import ChanDiagnosis, chan_diagnostic
from tools.render_well_map import MapPoint, WellMap, render_well_map
from tools.candidate_ranking import (
    CandidateQueues,
    CandidateRow,
    DocumentHit,
    FailurePrediction,
    FillageResult,
    InterventionMarker,
    InterventionRoute,
    OffsetResult,
    ProductionSeries,
    RankedWell,
    SeriesPoint,
    TriggerResult,
    UpliftEstimate,
    WellRanking,
    check_mro,
    check_offsets,
    detect_mechanical_signature,
    estimate_uplift,
    fillage_proxy,
    generate_draft_plan,
    generate_report,
    plot_production,
    predict_failure,
    query_wells,
    rank_candidates,
    route_intervention,
    schedule_rigs,
    search_well_history,
    trigger_scan,
)

__all__ = [
    "Confidence",
    "MechSignature",
    "OffsetVerdict",
    "ToolResult",
    "ToolStatus",
    "WaterMechanism",
    "DeclineFit",
    "fit_decline_curve",
    "ChanDiagnosis",
    "chan_diagnostic",
    "MapPoint",
    "WellMap",
    "render_well_map",
    "CandidateQueues",
    "CandidateRow",
    "DocumentHit",
    "FailurePrediction",
    "FillageResult",
    "InterventionMarker",
    "InterventionRoute",
    "OffsetResult",
    "ProductionSeries",
    "RankedWell",
    "SeriesPoint",
    "TriggerResult",
    "UpliftEstimate",
    "WellRanking",
    "fillage_proxy",
    "check_offsets",
    "detect_mechanical_signature",
    "predict_failure",
    "trigger_scan",
    "route_intervention",
    "estimate_uplift",
    "rank_candidates",
    "check_mro",
    "search_well_history",
    "generate_draft_plan",
    "generate_report",
    "schedule_rigs",
    "plot_production",
    "query_wells",
]
